/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Dimension
 */
export interface Dimension {
    /**
     * 
     * @type {number}
     * @memberof Dimension
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof Dimension
     */
    unit?: string;
}

/**
 * Check if a given object implements the Dimension interface.
 */
export function instanceOfDimension(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DimensionFromJSON(json: any): Dimension {
    return DimensionFromJSONTyped(json, false);
}

export function DimensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dimension {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
    };
}

export function DimensionToJSON(value?: Dimension | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'unit': value.unit,
    };
}

