/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * standrad error response for client and server errors
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    timestamp?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorResponseError interface.
 */
export function instanceOfErrorResponseError(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorResponseErrorFromJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorFromJSONTyped(json, false);
}

export function ErrorResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorResponseErrorToJSON(value?: ErrorResponseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'timestamp': value.timestamp,
        'message': value.message,
    };
}

