/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Extended
 */
export interface Extended {
    /**
     * 
     * @type {string}
     * @memberof Extended
     */
    amwayLabels?: string;
    /**
     * 
     * @type {string}
     * @memberof Extended
     */
    amwaySize?: string;
}

/**
 * Check if a given object implements the Extended interface.
 */
export function instanceOfExtended(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExtendedFromJSON(json: any): Extended {
    return ExtendedFromJSONTyped(json, false);
}

export function ExtendedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Extended {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amwayLabels': !exists(json, 'amwayLabels') ? undefined : json['amwayLabels'],
        'amwaySize': !exists(json, 'amwaySize') ? undefined : json['amwaySize'],
    };
}

export function ExtendedToJSON(value?: Extended | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amwayLabels': value.amwayLabels,
        'amwaySize': value.amwaySize,
    };
}

