/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Flags
 */
export interface Flags {
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    needSerialNumber?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    isBundle?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    isDurable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    isConfigurable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Flags
     */
    isDonation?: boolean;
}

/**
 * Check if a given object implements the Flags interface.
 */
export function instanceOfFlags(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FlagsFromJSON(json: any): Flags {
    return FlagsFromJSONTyped(json, false);
}

export function FlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flags {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'needSerialNumber': !exists(json, 'needSerialNumber') ? undefined : json['needSerialNumber'],
        'isBundle': !exists(json, 'isBundle') ? undefined : json['isBundle'],
        'isDurable': !exists(json, 'isDurable') ? undefined : json['isDurable'],
        'isConfigurable': !exists(json, 'isConfigurable') ? undefined : json['isConfigurable'],
        'isDonation': !exists(json, 'isDonation') ? undefined : json['isDonation'],
    };
}

export function FlagsToJSON(value?: Flags | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'needSerialNumber': value.needSerialNumber,
        'isBundle': value.isBundle,
        'isDurable': value.isDurable,
        'isConfigurable': value.isConfigurable,
        'isDonation': value.isDonation,
    };
}

