/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    altText?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    format?: string;
    /**
     * 
     * @type {number}
     * @memberof Image
     */
    galleryIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    imageType?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    publicUrl?: string;
}

/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'altText': !exists(json, 'altText') ? undefined : json['altText'],
        'format': !exists(json, 'format') ? undefined : json['format'],
        'galleryIndex': !exists(json, 'galleryIndex') ? undefined : json['galleryIndex'],
        'imageType': !exists(json, 'imageType') ? undefined : json['imageType'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'publicUrl': !exists(json, 'publicUrl') ? undefined : json['publicUrl'],
    };
}

export function ImageToJSON(value?: Image | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'altText': value.altText,
        'format': value.format,
        'galleryIndex': value.galleryIndex,
        'imageType': value.imageType,
        'url': value.url,
        'publicUrl': value.publicUrl,
    };
}

