/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Loyalty
 */
export interface Loyalty {
    /**
     * 
     * @type {number}
     * @memberof Loyalty
     */
    loyaltyProgramMultiplier?: number;
}

/**
 * Check if a given object implements the Loyalty interface.
 */
export function instanceOfLoyalty(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoyaltyFromJSON(json: any): Loyalty {
    return LoyaltyFromJSONTyped(json, false);
}

export function LoyaltyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Loyalty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loyaltyProgramMultiplier': !exists(json, 'loyaltyProgramMultiplier') ? undefined : json['loyaltyProgramMultiplier'],
    };
}

export function LoyaltyToJSON(value?: Loyalty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'loyaltyProgramMultiplier': value.loyaltyProgramMultiplier,
    };
}

