/* tslint:disable */
/* eslint-disable */
/**
 * Product App Microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorResponseAllOfErrorSubErrors
 */
export interface ValidationErrorResponseAllOfErrorSubErrors {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponseAllOfErrorSubErrors
     */
    parameter?: string;
    /**
     * 
     * @type {number}
     * @memberof ValidationErrorResponseAllOfErrorSubErrors
     */
    rejectedValue?: number;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponseAllOfErrorSubErrors
     */
    message?: string;
}

/**
 * Check if a given object implements the ValidationErrorResponseAllOfErrorSubErrors interface.
 */
export function instanceOfValidationErrorResponseAllOfErrorSubErrors(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ValidationErrorResponseAllOfErrorSubErrorsFromJSON(json: any): ValidationErrorResponseAllOfErrorSubErrors {
    return ValidationErrorResponseAllOfErrorSubErrorsFromJSONTyped(json, false);
}

export function ValidationErrorResponseAllOfErrorSubErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponseAllOfErrorSubErrors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameter': !exists(json, 'parameter') ? undefined : json['parameter'],
        'rejectedValue': !exists(json, 'rejectedValue') ? undefined : json['rejectedValue'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ValidationErrorResponseAllOfErrorSubErrorsToJSON(value?: ValidationErrorResponseAllOfErrorSubErrors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameter': value.parameter,
        'rejectedValue': value.rejectedValue,
        'message': value.message,
    };
}

